"""Generates the index.html page with a navigation tree of all converted files."""

from pathlib import Path
from html import escape

from .builder import OUT_ROOT, FILES_ROOT


INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home - dividendos</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <nav class="top-nav">
        <span class="nav-title">&#128193; dividendos</span>
    </nav>
    <main class="content index-page">
        <h1>File Index</h1>
        <p class="index-subtitle">Generated on {generated_date}</p>
        <div class="file-tree">
{tree_html}
        </div>
    </main>
    <footer>
        <p>Generated by dividendos</p>
    </footer>
    <script src="js/script.js"></script>
</body>
</html>"""


def _build_tree_html(directory: Path, rel_root: Path) -> str:
    """Recursively build an HTML tree of the files directory.

    Returns a string of nested <details>/<summary> elements for directories
    and <a> links for files.
    """
    items = []
    entries = sorted(directory.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower()))

    for entry in entries:
        rel = entry.relative_to(rel_root)
        name = entry.name

        if entry.is_dir():
            children_html = _build_tree_html(entry, rel_root)
            # Check if there are any .html files inside (recursively)
            has_html = any(f.suffix == '.html' for f in entry.rglob('*'))
            if not has_html and not children_html.strip():
                continue
            items.append(
                f'        <details class="folder" open>\n'
                f'            <summary class="folder-name">&#128193; {escape(name)}</summary>\n'
                f'            <div class="folder-contents">\n'
                f'{children_html}'
                f'            </div>\n'
                f'        </details>'
            )
        elif entry.suffix == '.html':
            # Build relative path from index.html to this file
            file_rel = rel.as_posix()
            display_name = entry.stem.replace('-', ' ').replace('_', ' ').title()
            items.append(
                f'        <div class="file-item">'
                f'<a href="files/{file_rel}">&#128196; {escape(display_name)}</a>'
                f'</div>'
            )

    return '\n'.join(items)


def generate_index() -> None:
    """Generate or update the index.html file at out/index.html."""
    from datetime import datetime

    if not FILES_ROOT.exists():
        FILES_ROOT.mkdir(parents=True, exist_ok=True)

    tree_html = _build_tree_html(FILES_ROOT, FILES_ROOT)

    if not tree_html.strip():
        tree_html = '        <p class="empty-state">No files yet. Add .md files to the <code>md/</code> directory and run the converter.</p>'

    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    index_html = INDEX_TEMPLATE.format(
        generated_date=now,
        tree_html=tree_html,
    )

    index_path = OUT_ROOT / 'index.html'
    index_path.write_text(index_html, encoding='utf-8')
    print(f"  Generated: index.html")